### ISSUE TITLE
Should IPNetwork become struct or is it too late?

### ISSUE THREAD

**Issue by moander** [aspnet/BasicMiddleware#103]

**Comment by davidfowl** [comment]
Not too late for 2.0.0, but @Tratcher why do we expose this type in the first place.

**Comment by Tratcher** [comment]
It's used here for address ranges: https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersOptions.cs#L32

**Comment by muratg** [comment]
Too late for 1.x
