### ISSUE TITLE
Clean up response compression

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BasicMiddleware#108]
Open items:
- More convenient Options
 - ~~Compression providers~~
 - ~~Compression negotiator~~
- accept-encoding q-value negotiation (perf)
- ~~should mime types be case sensitive? (No)~~
- ~~Make sure no negotiation happens / no bytes written if there's no body.~~
- ~~Flush~~
- Exception
- ~~Hook ISendFileFeature?~~
- API Review

Testing:
- ~~How much buffering does the gzip stream do?~~ 8kb
- ~~Integration test with WebListener, Kestrel,~~
- ~~IIS/Express~~
- ~~nginx~~ https://github.com/aspnet/BasicMiddleware/issues/123
- ~~Perf~~ https://github.com/dotnet/corefx/issues/12549

Release:
- [x] Bump version from 0.1.0 to 1.0.0 when ready

**Comment by muratg** [comment]
Putting in 1.1.0 for now. We can move it to 1.2.0 if we can't finish this off in time.

**Comment by Tratcher** [comment]
GZipStream allocations: https://github.com/dotnet/corefx/issues/12549

**Comment by muratg** [comment]
@Tratcher Per PM decision, version numbers for new packages will be 1.0.0-preview1 for the initial release. (Not 1.1.0-preview1)

**Comment by Tratcher** [comment]
Review feedback:

Remove the `AddResponseCompression(params string[])` overload, investigate defaults and wildcards instead. Text/*, Application/javascript

Try binding Options from Config

Should the services be registered as singleton or transient? Eilon said Singleton.

Split ResponseCompressionExtensions by services vs appbuilder.

Rename EnableHttps to EnableForHttps

**Comment by Tratcher** [comment]
Reading from config works pretty well:
```
{
  "section": {
    "EnableForHttps": true,
    "MimeTypes": ["text/plain", "text/html"]
  }
}
```
```
            services.AddResponseCompression(options =>
            {
                Configuration.GetSection("section").Bind(options);
            });
```

**Comment by Tratcher** [comment]
Possible default mime types (things used by the template, static files):
text/css
text/html
application/javascript

WebApi:
application/xml
text/xml
application/json
text/json
application/json-patch+json

Other:
text/plain

**Comment by Yves57** [comment]
Maybe adding "image/svg+xml" to the default types.

**Comment by Tratcher** [comment]
@Yves57 justification? We're not trying to capture every possible type, just the ones to make the 90% scenario work. I based this list on the files included in the full WebApp template, as well as those types from MVC/WebAPI.

**Comment by Tratcher** [comment]
Closing this now that we've worked through the main checklists. Further questions, feedback, etc. should be filed in new issues.

**Comment by Yves57** [comment]
@Tratcher Because SVG is a standard included in W3C recommandations. So I don't think it's "exotic"...
