### ISSUE TITLE
Fix NuGet package descriptions

### ISSUE THREAD

**Issue by Eilon** [aspnet/BasicMiddleware#129]
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/project.json
* Was: `ASP.NET Core basic middleware for:\r\nRewrite Url module.`
* Change to: `ASP.NET Core basic middleware for rewriting URLs. Includes:\r\n* Support for custom URL rewrite rules\r\m* Support for running IIS URL Rewrite module rules\r\n* Support for running Apache mod_rewrite rules.` (feel free to massage this a bit if it's not exactly right)

https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Buffering/project.json
* Was: `ASP.NET Core middleware for buffering response bodies.`
* No change.

https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/project.json
* Was: `ASP.NET Core basic middleware for:\r\nX-Forwarded-* headers to forward headers from a proxy.\r\nHTTP method override header.`
* Change to: `ASP.NET Core basic middleware for supporting HTTP method overrides. Includes:\r\nX-Forwarded-* headers to forward headers from a proxy.\r\nHTTP method override header.`

https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.ResponseCompression/project.json
* Was: `ASP.NET Core middleware for HTTP Response compression.`
* No change.

**Comment by Eilon** [comment]
@muratg make sure you triage this as well to set milestone/labels.

**Comment by muratg** [comment]
@mikaelm12 let's get these in right after branching for 1.1.0-preview1
