### ISSUE TITLE
Add support for the CustomResponse action in Url Rewrite

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/BasicMiddleware#135]
> A CustomResponse action causes the URL Rewrite Module to respond to the HTTP client by using a user-specified status code, subcode, and reason. Use of a CustomResponse action implies that no subsequent rules are evaluated for the current URL after this action is performed.
> CustomResponse action has the following configuration options:
> - statusCode – Specifies the status code to use in response to the client.
> - subStatusCode – Specifies the substatus code to use in response to the client.
> - statusReason – Specifies the reason phrase to use with the status code.
> - statusDescription – Specifies the one line description to put in the body of the response.

**Comment by davidpeden3** [comment]
addressed in https://github.com/aspnet/BasicMiddleware/pull/200

**Comment by davidpeden3** [comment]
duplicate https://github.com/aspnet/BasicMiddleware/issues/56

**Comment by mikaelm12** [comment]
Resolved in https://github.com/aspnet/BasicMiddleware/pull/200
