### ISSUE TITLE
DisableResponseBuffering does not work as expected in ResponseCompression

### ISSUE THREAD

**Issue by pakrym** [aspnet/BasicMiddleware#137]
Writes would not flush automatically in the following code.

```
 app.Map("/slownb", a =>
            {
                a.UseResponseCompression();
                a.Run(async w =>
                {
                    w.Response.Headers["Content-Type"] = "text/html";

                    var nb = w.Features.Get<IHttpBufferingFeature>();
                    nb.DisableResponseBuffering();

                    while (!w.RequestAborted.IsCancellationRequested)
                    {
                        await w.Response.WriteAsync("1");
                        await Task.Delay(TimeSpan.FromSeconds(0.1));
                    }
                });
            });
```

@Tratcher

**Comment by Tratcher** [comment]
By design, call Flush/Async.

**Comment by pakrym** [comment]
Then why have it? Flush works even without `DisableResponseBuffering`

**Comment by Tratcher** [comment]
Only on Core, not on Net 4.5.1.

**Comment by pakrym** [comment]
I'm concerned that it's not consistent with ResponseBuffering in buffering if you call `DisableResponseBuffering` writes are immediately written to the wire.

**Comment by Tratcher** [comment]
@davidfowl

**Comment by davidfowl** [comment]
It's pretty strange that the same interface has different behavior depending on who implements it. Wouldn't it be better to make them all consistently disable all buffering all the time when this method is called?

**Comment by Tratcher** [comment]
Are you saying that because that's the name of the feature, or because that's the behavior end-users actually want? When I had this discussion with @DamianEdwards his primary concern was that we make Flush work.

The current implementation is a compromise that allows both compression and the ability to Flush, if supported.

**Comment by davidfowl** [comment]
Because the contract of the interface says get all buffering out of the way. An explicit flush shouldn't be required to make this work. Flushing without calling disable buffering can do this can't it?

**Comment by Tratcher** [comment]
Not on Net451

**Comment by Tratcher** [comment]
Offline discussion: DisableResponseBuffering should disable compression on .NET 4.5.1 and auto-flush writes on .NET Core.

**Comment by muratg** [comment]
https://github.com/aspnet/BasicMiddleware/pull/154/files
