### ISSUE TITLE
Parse invalid negate sets ignoreCase instead of negate in UrlRewrite

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#138]
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/UrlRewriteFileParser.cs#L152

@jkotalik @mikaelm12 @muratg

**Comment by mikaelm12** [comment]
Fixed in https://github.com/aspnet/BasicMiddleware/pull/140
