### ISSUE TITLE
Enabled rule attribute never used

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#139]
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/UrlRewriteFileParser.cs#L58

@mikaelm12 @muratg @jkotalik

**Comment by jkotalik** [comment]
That issues doesn't fix the enable rule never being used. It should be added here:
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/UrlRewriteRuleBuilder.cs#L31
as a check to see if we should be creating the rule in the first place.

**Comment by mikaelm12** [comment]
The enabled flag on the builder is actually being used here to determine if each rule should be added
https://github.com/aspnet/BasicMiddleware/blob/d57149f9c04ff410f9a146ed686f15693e962137/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/UrlRewriteFileParser.cs#L51-L54
