### ISSUE TITLE
Force HTTPS in beta8 broken

### ISSUE THREAD

**Issue by robfarmergt** [aspnet/BasicMiddleware#14]
I was using the following suggestion to force SSL prior to beta8: https://github.com/aspnet/BasicMiddleware/issues/10

It seems the same code is causing a redirect loop for some reason. I can't seem to get it to work.

**Comment by Tratcher** [comment]
If you're now using the HttpPlatformHandler then you should add `app.UseIISPlatformHandler()` to make sure your scheme gets forwarded. https://github.com/aspnet/Hosting/issues/364 https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs#L67-L78

**Comment by robfarmergt** [comment]
We are hosting in an Azure Web App, any idea if that would work? I'm sure it would locally.

**Comment by Tratcher** [comment]
Yes it should. Azure doesn't have the latest HttpPlatformHandler yet, but it has supported scheme forwarding since v1.0.

**Comment by robfarmergt** [comment]
Thank you, adding that to the pipeline worked!
