### ISSUE TITLE
patternSyntax parsing behavior

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#145]
Change `WildCard` to `Wildcard`
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/PatternSyntax.cs#L9
OR
Parse the Enum ignoring case
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/UrlRewriteFileParser.cs#L64

@mikaelm12

**Comment by BrennanConroy** [comment]
Also look at the other Enums like MatchType, found examples of both uppercase and camelCase on the interwebz

**Comment by mikaelm12** [comment]
We should definitely change the `WildCard` enum to `Wildcard` for consistency with the Url Rewrite reference doc and I think that we should also do case insensitive parsing of enums.

Thoughts @Tratcher @natemcmaster ?

**Comment by natemcmaster** [comment]
> ... change the WildCard enum to Wildcard for consistency with the Url Rewrite reference doc and I think that we should also do case insensitive parsing of enums.

Yes to both.

**Comment by mikaelm12** [comment]
Fixed in https://github.com/aspnet/BasicMiddleware/pull/160
