### ISSUE TITLE
LogicalGrouping check is incorrect

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#146]
When parsing `logicalGrouping` in `Conditions` we use `RewriteTags.MatchType`, we need to add a `RewriteTags.LogicalGrouping` constant and use that for `logicalGrouping` parsing

@mikaelm12

**Comment by mikaelm12** [comment]
Fixed in https://github.com/aspnet/BasicMiddleware/pull/160
