### ISSUE TITLE
IISUrlRewriteBuilder and RegexOptions.ECMAScript

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BasicMiddleware#147]
URL Rewrite uses the ECMAScript spec to parse regular expressions (see https://www.iis.net/learn/extensions/url-rewrite-module/url-rewrite-module-20-configuration-reference). Currently the [IISUrlRewriteBuilder](https://github.com/aspnet/BasicMiddleware/blob/89a6f453ce5eb85a0c41cf3153d8f790a5fa2103/src/Microsoft.AspNetCore.Rewrite/Internal/IISUrlRewrite/UrlRewriteRuleBuilder.cs#L69-L74) does not use [`RegexOptions.ECMAScript`](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regexoptions%28v=vs.110%29.aspx) which means the regex pattern matching uses canonical instead of ECMAScript matching.

The difference may cause subtle differences in how IIS would have matched a pattern vs how the rewrite middleware does (such as what matches the `\w` character group) or self-referencing capture groups.

**Comment by muratg** [comment]
@mikaelm12 Could we check what Apache modrewrite uses for regex syntax? We should make sure we use the right regex syntax for that as well.

- UrlRewrite should use ECMAScript syntax
- ModRewrite should use whatever Apache uses
- Code based rules should use C# default syntax

**Comment by mikaelm12** [comment]
From the mod_rewrite doc

> mod_rewrite uses the Perl Compatible Regular Expression vocabulary.

From the url rewrite doc

>  Perl compatible (ECMAScript standard compliant) regular expression syntax

 @natemcmaster  Also something to note is that the `RegexOptions.ECMAScript` flag cannot be used with the `RegexOptions.CultureInvariant` flag which is currently being set as well.

**Comment by mikaelm12** [comment]
I was having trouble with making this change but it turns out that there is an inconsistency in the docs
It turns out that you can only use the `RegexOptions.ECMAScript` flag with the IgnoreCase and Multiline flags

These [RegexOption docs](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regexoptions(v=vs.110).aspx) say about `RegexOptions.ECMAScript`

> This value can be used only in conjunction with the IgnoreCase, Multiline, and Compiled values. 


But these [docs](https://msdn.microsoft.com/en-us/library/yd1hzczs(v=vs.110).aspx#ECMAScript Matching Behavior)  say

> The RegexOptions.ECMAScript option can be combined only with the RegexOptions.IgnoreCase and RegexOptions.Multiline options

which is correct. So we also have to removed the compiled flag as well.

**Comment by muratg** [comment]
@mikaelm12 Would removing the compiled flag be a perf concern?

**Comment by mikaelm12** [comment]
@muratg Yes it is a perf concern. If we wan't to use the ECMAScript option we have to remove the compiled flag though.

**Comment by natemcmaster** [comment]
IIRC you can still use .Compiled on desktop .NET. We should measure perf impact to see if it actually matters.

**Comment by mikaelm12** [comment]
So I did some basic perf testing and with large numbers of iterations ( > 10 Million) the absence of the compiled flag caused an about 13% hit to performance.  Less than 1 Million iterations had less than a 5% effect. 

Thoughts @muratg @Tratcher

**Comment by Tratcher** [comment]
Correctness trumps perf. How well do you understand the functional differences of ECMAScript?

**Comment by mikaelm12** [comment]
Not well tbh.

**Comment by muratg** [comment]
https://msdn.microsoft.com/en-us/library/yd1hzczs(v=vs.110).aspx#ECMAScript

**Comment by mikaelm12** [comment]
Damian says don't use the ECMAScript flag.

**Comment by muratg** [comment]
Closing per @DamianEdwards's decision.
