### ISSUE TITLE
Remove '?' prefix from QUERY_STRING server variable

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#148]
https://www.iis.net/learn/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#Accessing_URL_Parts_from_a_Rewrite_Rule
Shows the value of `{QUERY_STRING}` from `http://www.mysite.com/content/default.aspx?tabid=2&subtabid=3` to be `tabid=2&subtabid=3`

I also, did a quick test with the IIS Rewrite Module and it doesn't seem to include `?` in the `{QUERY_STRING}`

**Comment by jkotalik** [comment]
Good catch. Should be a one line fix in the server variables. Check mod_rewrite if you get the chance for its behavior.

**Comment by BrennanConroy** [comment]
I will be checking mod_rewrite later

**Comment by BrennanConroy** [comment]
mod_rewrite has the same issue since they both use the `QueryStringSegment` class
