### ISSUE TITLE
ExactMatch should set BackReference

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#149]
The back reference will just be the pattern
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/UrlMatches/ExactMatch.cs#L21

**Comment by muratg** [comment]
We should add a couple test cases for the use cases.

**Comment by mikaelm12** [comment]
So the BackReference isn't set here because a string compare is being used here in stead of a regex match. We can either do a regex match here or we have to change the BackReference to be something other than a `GroupCollection`
Thoughts @Tratcher @natemcmaster @BrennanConroy?

**Comment by BrennanConroy** [comment]
Fix the `GroupCollection`!

**Comment by jkotalik** [comment]
Seriously. I couldn't use an dict/list because it would add an extra O(n) operation to transfer it. IMO group collection should have an interface similar to a list, but unfortunately there isn't.

**Comment by mikaelm12** [comment]
@muratg The 1.1.0 fix for this is to just do a regex match instead of a string compare and set the back reference with the `GroupCollection `from the regex match. The 1.2.0 solution for fixing the `TrackAllCaptures` will need to use it

**Comment by muratg** [comment]
#141 is tracking this work.
