### ISSUE TITLE
mod_rewrite redirect flag should allow no status code value

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/BasicMiddleware#152]
On a `RewriteRule` the `[R]` flag allows an optional status code value but currently we require a status code value

**Comment by jkotalik** [comment]
Default to 302?

**Comment by BrennanConroy** [comment]
Looks like it
http://httpd.apache.org/docs/current/rewrite/flags.html#flag_r

**Comment by Tratcher** [comment]
hmm, what about these other parts?
`The status code specified need not necessarily be a redirect (3xx) status code. However, if a status code is outside the redirect range (300-399) then the substitution string is dropped entirely, and rewriting is stopped as if the L were used.`

`In addition to response status codes, you may also specify redirect status using their symbolic names: temp (default), permanent, or seeother.`
