### ISSUE TITLE
Url Rewrite and Repo name suggestion

### ISSUE THREAD

**Issue by imranbaloch** [aspnet/BasicMiddleware#171]
I just a small suggestion to make the rewrite name more specific. For example, I suggest UseUrlRewriter instead of UseRewriter and so on.  

Second thing I think the repo name (BasicMiddleware) is little bit confusing. My first thought was it includes Basic Auth Middleware. Can we give it a better name like CommonMiddlewares/SharedMiddlewares or? 

Just my 2 cents.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
