### ISSUE TITLE
Compression: Add additional checks in ShouldCompress

### ISSUE THREAD

**Issue by spboyer** [aspnet/BasicMiddleware#186]
Needed additional checks in https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.ResponseCompression/ResponseCompressionProvider.cs#L107

* When 'Cache-Control: no-transform' is present, content should not be gzipped and 'Vary' Response header should not be present

**Comment by Tratcher** [comment]
Spec reference?

**Comment by spboyer** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.5

**Comment by JunTaoLuo** [comment]
@spboyer How are you using this feature? Also the cache directive is meant to be used by proxies and caches so it's not clear that it applies to the response compression middleware here.

**Comment by spboyer** [comment]
Looking at the tests for should compress, even though Kestrel is not a proxy it may receive no-transform and should not modify the resource being requested.

**Comment by JunTaoLuo** [comment]
@spboyer which tests are you referring to? I still don't see why the `no-transform` directive, which only applies to proxies and caches, would be significant here. The compression is a middleware on the server and shouldn't be looking for and changing its behaviour based on cache related headers. If the client wants a un-transformed resource, it should specify `Accept-Encoding: identity` to obtain the untransformed version.

**Comment by spboyer** [comment]
The "tests" i was referring to is the [ShouldCompressResponse](https://github.com/aspnet/BasicMiddleware/blob/f0b44ac7b51ffd53051aeef3846c1cdaf07e9bc6/src/Microsoft.AspNetCore.ResponseCompression/ResponseCompressionProvider.cs#L107) and [GetCompressionProvider](https://github.com/aspnet/BasicMiddleware/blob/f0b44ac7b51ffd53051aeef3846c1cdaf07e9bc6/src/Microsoft.AspNetCore.ResponseCompression/ResponseCompressionProvider.cs#L63).

Noted the `Accept-Encoding: identity` should be passed for a non-Encoded. Closing issue.
