### ISSUE TITLE
Compression: Vary Header not returned when content gzipped

### ISSUE THREAD

**Issue by spboyer** [aspnet/BasicMiddleware#187]
Response header should contain
```
Vary: Accept-Encoding
```

when content is gzipped. IIS compression currently adds header.

**Comment by Tratcher** [comment]
There's some debate over who should be setting this. Right now the cache headers are set by the resource (e.g. the ResponseCache attribute on the MVC action).

I guess you could consider this an opt-out header and compare it to the CookieAuth middleware always opting out of all caching.

Does IIS add the Vary even for non-cacheable responses?

**Comment by spboyer** [comment]
My understanding, would need confirmation from IIS team, is that if the `Accept-Encoding` header is sent then IIS responds with the Vary, otherwise no.
