### ISSUE TITLE
Source querystring is not preserved for redirects when target doesn't have a querystring

### ISSUE THREAD

**Issue by GuardRex** [aspnet/BasicMiddleware#188]
@bartmax found this at ...

https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/RedirectRule.cs#L81

@bartmax suggested for L81 ...
```
response.Headers[HeaderNames.Location] = 
    pathBase + newPath + context.HttpContext.Request.QueryString;
```
... to preserve it for the redirect when the `newPath` doesn't have one.

If you're wondering why he didn't open this, I asked him, and he responded in code ...
```
Lazy<Bart> bart => OpenIssue();
```
:smile:

**Comment by muratg** [comment]
@mikaelm12 could you investigate?

**Comment by Bartmax** [comment]
wohooo!! 👍
