### ISSUE TITLE
Users are able to make site throw an exception when using ResponseCaching middleware.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/BasicMiddleware#189]
using the `ResponseCachingMiddleware` with `VaryByQueryKeys`

```
[ResponseCache(CacheProfileName = "DefaultCache", VaryByQueryKeys = new string[] { "id" })]
```

open chrome inspector
tick disable cache
go to page that uses a `ResponseCache` with `VaryByQueryKeys` 

![image](https://cloud.githubusercontent.com/assets/3386797/21001439/1c2d671e-bcff-11e6-9de2-7bd5518a9327.png)

it throws: 
InvalidOperationException: 'VaryByQueryKeys' requires the response cache middleware.

closing the inspector or untick disable cache work fine.

Using fiddler, adding `Pragma: no-cache` header is enough to make the site throw an exception.

**Comment by GuardRex** [comment]
Confirmed here.

![capture](https://cloud.githubusercontent.com/assets/1622880/21001524/67a14a9e-bce6-11e6-8442-e8968c3473c2.PNG)

**Comment by ctolkien** [comment]
We had these logs start to turn up in AppInsights as well, we've had to disable ResponseCaching :/

**Comment by Bartmax** [comment]
bad repo, mind comment again here: https://github.com/aspnet/ResponseCaching/issues/85
