### ISSUE TITLE
www to non-www

### ISSUE THREAD

**Issue by alvipeo** [aspnet/BasicMiddleware#193]
Hi! I'm trying to do a simple thing - force 301 for www to non-www. Like described here - http://stackoverflow.com/questions/41205435/asp-net-core-1-1-url-rewriting-www-to-non-www. Can you please tell me why it doesn't work?

Thank you!

**Comment by jkotalik** [comment]
Hey, I just added a response on SO. The issue is that the regex match is done on the path/query string rather than the whole URL. This is standard for most/ all url rewriters, so I created a quick custom one with an Action<RewriteContext>.

**Comment by muratg** [comment]
Closing this and keeping #194 open instead.
