### ISSUE TITLE
Add a Brotli Compression Provider

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/BasicMiddleware#217]
[This](https://tpeczek.blogspot.co.uk/2017/03/extending-aspnet-core-response.html) great post by Tomasz Pęczek shows how to add Brotli compression today using Brotli.NET which is a .NET wrapper around the native Brotli DLL. ASP.NET Core has made a big deal about performance, this should be a higher priority.

Related issue '[Add a Priority to each Response Compression Provider](https://github.com/aspnet/BasicMiddleware/issues/216)' would also need to be addressed.

**Comment by jbayardo** [comment]
Might want to sue the version in CoreFX Labs for this: https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.IO.Compression.Brotli

**Comment by muratg** [comment]
@jkotalik This is not ready yet, but will be once CoreFX packages are in a usable state. 

cc @joshfree FYI

**Comment by joshfree** [comment]
Yes, this is one of the next things @ianhays will be working on.  https://github.com/dotnet/corefx/issues/24826

**Comment by jkotalik** [comment]
https://github.com/dotnet/corefx/issues/24826 was just finished. We can consume this soon. @muratg we still want to target this for 2.1, correct?

**Comment by muratg** [comment]
@jkotalik possibly, but we'll need to prioritize it with other items. 

cc @glennc

**Comment by ianhays** [comment]
Out of curiosity, @muratg are you still planning on including brotli support for 2.1 by consuming the [CoreFX Brotli library being added in .net core 2.1?](https://github.com/dotnet/corefx/tree/master/src/System.IO.Compression.Brotli)

FYI: @joshfree

**Comment by muratg** [comment]
@ianhays It's not currently in 2.1 list.   cc @DamianEdwards

**Comment by joshfree** [comment]
It would be nice if ASP.NET Core exposed this in 2.1 if there's still time.

https://github.com/dotnet/corefx/issues/25785

**Comment by DamianEdwards** [comment]
I'd love for us to have this in 2.1, but there are other items ahead of it right now and given where we are it seems unlikely we'll get it in.

**Comment by joshfree** [comment]
@muratg @glennc can you prioritize completing this work for .NET Core 2.2?

**Comment by muratg** [comment]
@joshfree I don't think anything changed since @DamianEdwards's comment. He owns the priorities.

**Comment by khellang** [comment]
This should be a quick pull request from the community, right?

**Comment by RehanSaeed** [comment]
Might not be as simple as you think. To do this, https://github.com/aspnet/BasicMiddleware/issues/216 also needs to be implemented.

**Comment by Tratcher** [comment]
To make it useful that is...

**Comment by tpeczek** [comment]
Also the fact that System.IO.Compression.Brotli (unless I've missed something) is .NET Core only might be a problem.

**Comment by joshfree** [comment]
Thanks folks for getting this into the 2.2 milestone!
