### ISSUE TITLE
Add UseHttpsRedirect middleware

### ISSUE THREAD

**Issue by danroth27** [aspnet/BasicMiddleware#240]
We need an easier way to redirect to HTTPS that works across different environments (specific port in development, default port in production)

- HttpsRedirectOptions with port and status code (default to temporary)
- Default UseHttpsRedirect overload only. Should provide an error if HttpsRedirectOptions not configured (use marker service pattern)
- Add default config schema for the HTTPS port (`Microsoft:AspNetCore:HttpsRedirect:Port`)
- This middleware can invoke the URL rewrite middleware for its implementation

**Comment by Tratcher** [comment]
Seems a bit redundant to have this functionality implemented in rewrite, MVC, and it's own middleware. Seems like you're primarily asking for easier configuration.

**Comment by danroth27** [comment]
If at first you don't succeed . . . :smile:

Yes, we are looking for a single gesture that enables HTTPS redirect functionality that works during development and after you publish to production. Do you have any alternative proposals on how to do that?

**Comment by Tratcher** [comment]
You can do this with rewrite, the only trick is getting the port number.

**Comment by danroth27** [comment]
Right. We want the port number to come out of config through options, but we didn't want to create yet another config format for rewrite rules in JSON. Hence the idea to create a targeted middleware for this common scenario.

**Comment by muratg** [comment]
@DamianEdwards FYI moving this out.

**Comment by jkotalik** [comment]
Finished by https://github.com/aspnet/BasicMiddleware/commit/758f9fcea590dbaf7294c940b2f7f32f01927379 except for the config.

**Comment by muratg** [comment]
@jkotalik good to close?
