### ISSUE TITLE
Remote IP on Reverse Proxy scenarios

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BasicMiddleware#256]
_From @luisgizirian on July 29, 2017 17:2_

Why is that `Context.Connection.RemoteIpAddress` supplies the Proxy's address in scenarios where `ForwardedHeadersOptions` were applied (either automatically by UseIISIntegration or manually), but `Context.Request.Headers["X-Forwarded-For"][0]` gives me the right address?

If I don't know beforehand the `ForwardedHeadersOptions.KnownProxies`, Is it possible to use the first X-Forwarded-For address to pre-fill `Context.Connection.RemoteIpAddress`? (`ForwardedHeadersOptions.ForwardLimit = 1` its default. And `RequireHeaderSymmetry = false` ) so I always get the Client/Browser IP address no matter what?

Tested scenarios (all based on ASPNET Core 2 preview 2):

* NGINX to Kestrel (single Azure Ubuntu VM)
* NGINX to Kestrel (2 Azure Ubuntu VMs)
* NGINX to Azure App Service to Kestrel (don't ask why, just did)

An app comparing and writing back both values, following this document (https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction) is all you need.

Quick short-circuit: `Configure` in Startup.cs:

```
app.Run(async (context) => await context.Response.WriteAsync("RemoteIPAddress property: " + context.Connection.RemoteIpAddress.ToString() + "\nX-Forwarded-For [0] Header: " + context.Request.Headers["X-Forwarded-For"][0] ));
                })
```

Please advice.

(my apologies if this is not the right place to post this question)

_Copied from original issue: aspnet/KestrelHttpServer#1974_

**Comment by Tratcher** [comment]
Can you share all of the headers in your scenario? There are known cases where ForwardedHeaders fails to process some kinds of input.

**Comment by luisgizirian** [comment]
So sorry. Moved on and took those environments down (damn cost savings!).
I'm using the x-forwarded-for header right away cause I needed to solve a
production scenario.

**Comment by muratg** [comment]
Not enough information on this bug so closing it.  If anyone has similar issues, please file another one with details.

**Comment by darting** [comment]
Hi there .. I have same issue when the app running on docker container ..

![image](https://user-images.githubusercontent.com/4946661/49139704-7366e080-f32d-11e8-9514-3b612945b2d2.png)

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

The results in your last screen shot look correct, what problem are you having specifically?
