### ISSUE TITLE
Add Akamai True-Client-IP support

### ISSUE THREAD

**Issue by h0useRus** [aspnet/BasicMiddleware#261]
Could you add Akamai True-Client-IP for ForwardedHeaders, or make it more modular for injecting custom headers handlers?

**Comment by Tratcher** [comment]
What's the format? It may be as easy as changing the default header name if the format matches: https://github.com/aspnet/BasicMiddleware/blob/347d1abfce8c257125bea17067f10cf30ce85396/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersOptions.cs#L16

**Comment by h0useRus** [comment]
Yes, we can, but then we loosing XForwardedFor header if Akamai header not exists and do extra configuration logic based on hosting environment.

**Comment by Tratcher** [comment]
How about adding a separate instance of UseForwardedHeaders that specifies the Akamai header name? They can stack.

That thread doesn't show the contents of the header.

Yes, IPv6 is supported. 
https://github.com/aspnet/BasicMiddleware/blob/347d1abfce8c257125bea17067f10cf30ce85396/test/Microsoft.AspNetCore.HttpOverrides.Tests/IPEndPointParserTest.cs#L16-L18

**Comment by h0useRus** [comment]
Good point to know, hank you it really solve, not best way, but works.

Here is official documentation from Akamai https://community.akamai.com/videos/1232

Got it, Great thanks.
