### ISSUE TITLE
Change redirect on HttpsRedirectionOptions from 301 to 302

### ISSUE THREAD

**Issue by javiercn** [aspnet/BasicMiddleware#271]
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionOptions.cs#L16

It's painful if a redirection to the wrong url happens (for example due to a misconfiguration caused by the lack of launchSettings.json)

This should be a 302 instead.

**Comment by Tratcher** [comment]
We'll rely on HSTS for the permanence aspect, that has more configurable caching policies.
