### ISSUE TITLE
Determine how CookieOptions.IsEssential applies to ChangeCookieAction 

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BasicMiddleware#283]
https://github.com/aspnet/BasicMiddleware/blob/f813ee4d970dc7130acd4afd410cb95ab2305cfa/src/Microsoft.AspNetCore.Rewrite/Internal/UrlActions/ChangeCookieAction.cs#L43

RE: aspnet/Security#1561

When this new policy is applied all non-essential cookies will be suppressed. We need to determine how that applies in this context. How would someone configure it?

@blowdart, @jkotalik

**Comment by jkotalik** [comment]
Interesting. As these actions are only obtained from ModRewrite rules, it would be tough to make changing the cookie configurable without changing the syntax. We could add a property on the RewriteOptions to say someone if the cookies are essential or not.

**Comment by muratg** [comment]
If we get to the decision by preview1, we can bring this back. Otherwise, postponing the bug to the next preview.

**Comment by muratg** [comment]
Triage decision: closing this. If we hear from folks that they want/need this, we'll reconsider.
