### ISSUE TITLE
Test Failure: Microsoft.AspNetCore.ResponseCompression.Tests.ResponseCompressionMiddlewareTest.FlushBody_CompressesAndFlushes [FAIL]

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#298]
Saw this happen on AppVeyor: https://ci.appveyor.com/project/aspnetci/basicmiddleware/build/1.0.810. May be a flaky test. @Tratcher thoughts?
@ryanbrandenburg if you see this happen on the CI, feel free to disable it.

**Comment by Eilon** [comment]
@muratg - critical now or 2.2.0-mq?

**Comment by ryanbrandenburg** [comment]
It looks like this failed 100% of the time on TC for a while, but hasn't failed since.

**Comment by muratg** [comment]
@ryanbrandenburg Ran but hasn't failed, or didn't run (disabled) hence hasn't failed? 

If the former, is this one good to close?

**Comment by ryanbrandenburg** [comment]
Yeah, it's been running since, I'll close this out.
