### ISSUE TITLE
UseForwardedHeaders not supporting IPv6 addresses?

### ISSUE THREAD

**Issue by rhegner** [aspnet/BasicMiddleware#302]
My app runs behind Ngnix and I'm trying to get client's IP address using `Connection.RemoteIpAddress`.

The request contains a `X-Forwarded-For` header like this: `::ffff:xxx.xxx.xxx.xxx:12345` and it does not seem to be recognized by the middleware using the following settings: 

    app.UseForwardedHeaders(new ForwardedHeadersOptions {  ForwardLimit = null, RequireHeaderSymmetry = false,  ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor });

If I set the same header manually to a IPv4 address, everything works as expected.

So does not middleware not support IPv6?

**Comment by Tratcher** [comment]
IPv6 is supported. That value isn't well formatted though, it's supposed to be `[::ffff:xxx.xxx.xxx.xxx]:12345`. Raw IPv6 addresses can't have ports appended without the brackets, the colons become ambiguous.

**Comment by muratg** [comment]
This was fixed in 2.2. If you still see issues, please let us know.
