### ISSUE TITLE
Consider adding a RequireHttps middleware

### ISSUE THREAD

**Issue by rynowak** [aspnet/BasicMiddleware#31]
We have [RequireHttps] in MVC as a filter that redirects you to `https://` - we should consider adding the same kind of thing as a middleware.

**Comment by Eilon** [comment]
BTW in MVC it's called `RequireHttpsAttribute`. Plus, definitely want to make sure it supports custom SSL ports, as we recently added to MVC as well: https://github.com/aspnet/Mvc/pull/4113

**Comment by rynowak** [comment]
Fixed, thanks!

**Comment by davidfowl** [comment]
It should probably share the options and all that.

**Comment by muratg** [comment]
Do we want to do this for RC2?  Doesn't seem to hard, though I'm not sure about the testing.

**Comment by Eilon** [comment]
If we want MVC and this middleware to share the option value (not a bad idea, I think), then we'd need a little bit of design on this. I don't think we've ever had this kind of sharing of configuration data before.

**Comment by davidfowl** [comment]
Cors and authz do this I think?

**Comment by BrennanConroy** [comment]
Currently SslPort is the only option the RequireHttps is using. It resides in MvcOption right now, but ideally we wouldn't have the RequireHttps Middleware depending on Mvc. What should we do about this?

CORS has the CorsPolicy class which Mvc depends on to share options, we could do the same thing and have Mvc depend on BasicMiddleware...

**Comment by cwe1ss** [comment]
I don't think it's necessary to share the options. I guess many people will use only one of both methods.  And since HTTPS will get more and more common, people will just want to forward everything to HTTPS - hence I believe that having a middleware is even more important than having the `RequireHttpsAttribute`.

Not sharing the options would simplify this middleware. But of course, +1 on supporting custom ports. This is a must-have for Azure Service Fabric.

**Comment by Tratcher** [comment]
We may do this as part of the UrlRewrite project

**Comment by Eilon** [comment]
@Tratcher I'm parking on your plate in the meantime.

**Comment by Tratcher** [comment]
This was added to the Rewrite middleware. https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/RewriteOptionsExtensions.cs#L96. I don't think we need an independent middleware for it. @muratg I recommend we close this as done for 1.1.

**Comment by rynowak** [comment]
I agree, this is a better solution :+1:
