### ISSUE TITLE
Make HttpRedirectionMiddleware not redirect to https if no HttpsPort is provided.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#318]
Fundamental issue is that apps will break if deployed to production that have not configured HTTPS (other than antares). At the last step of the middleware port checking, we currently set the HTTPS port to redirect to 443 if no port is found. Instead of that behavior, if no port is found to redirect to, we simply do not redirect the HttpRequest.

**Comment by Tratcher** [comment]
No, this fails every reverse proxy scenario.

**Comment by jkotalik** [comment]
For reverse proxy scenarios, we may need people to explicitly set the port (443 for instance) when behind a reverse proxy.

**Comment by Tratcher** [comment]
A security feature like this can't silently turn itself off. It's ok to have an off switch, but it can't turn itself off.

@blowdart

**Comment by blowdart** [comment]
What @Tratcher said, except with more "Dear god no" screaming

**Comment by jkotalik** [comment]
cc/ @DamianEdwards @davidfowl @javiercn

**Comment by Tratcher** [comment]
Note the no-https template is the primary mitigation for this issue.

**Comment by Eilon** [comment]
Also should log at Debug/Trace if the HTTPS redirect middleware ran but did not redirect.

**Comment by Eilon** [comment]
No logging if it's already HTTPS. We thought it ought to log if it *couldn't* redirect because it couldn't find the "desired" port in the configuration (or wherever).

**Comment by Tratcher** [comment]
No, that's a fatal configuration error that should be crashing the app.

**Comment by DamianEdwards** [comment]
Nah, don't agree.

**Comment by muratg** [comment]
Not doing this in RC1.

Current behavior has some usability issues that can be discovered pretty quickly by our users.

**Comment by javiercn** [comment]
> Current behavior has some usability issues that can be discovered pretty quickly by our users.

@muratg What does this mean?

**Comment by DamianEdwards** [comment]
Indeed, why is this punted?

**Comment by Eilon** [comment]
Yeah per our mtg the other day we need to do this in 2.1.0.

**Comment by henkmollema** [comment]
Perhaps this warrants an announcement? Applications upgrading from preview2 to RC1 suddenly don't redirect to HTTPS anymore with the default settings.

**Comment by DamianEdwards** [comment]
Agreed. Justin or Chris, could you post an announcement of this change in the RC1 milestone please.

**Comment by jkotalik** [comment]
I'll go ahead and post one.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/301

**Comment by henkmollema** [comment]
Thanks Justin!
