### ISSUE TITLE
URL rewrite canot get original url

### ISSUE THREAD

**Issue by yemin82** [aspnet/BasicMiddleware#319]
/// <summary>
        /// Executes the middleware.
        /// </summary>
        /// <param name="context">The <see cref="HttpContext"/> for the current request.</param>
        /// <returns>A task that represents the execution of this middleware.</returns>
        public Task Invoke(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            context.Response.Headers["X-Original-URL"] = context.Request.GetEncodedUrl();

**Comment by muratg** [comment]
@yemin82 Not sure what your issue is. Please file another issue with more details if you're still having issues.
