### ISSUE TITLE
Consider adding a 'correlationId' middleware

### ISSUE THREAD

**Issue by muratg** [aspnet/BasicMiddleware#32]
_From @rynowak on February 24, 2016 23:3_

It's a common pattern (like WCF activity ID) to create a correlation id and use it across multiple services with logging. This way if your logs all go to the same store you can associate all of the business processes across service/server boundaries that are part of the same unit of work. 
1. Front-end server creates a correlation ID and creates a log scope
2. Front-end server stashes the correlation ID in a way that some other code can get it (http context extension?)
3. Front-end server makes a call to another service - propagates the ID by taking it out of http context and passing it via a header (http client)
4. Back-end server reads the header and creates a log scope
5. And so on...

There's 3-5 lines of boilerplate required to do steps 1,2, and 4, and we could easily make a middleware that does it for you.

We might want to add an extension method for step 3.

_Copied from original issue: aspnet/Logging#371_

**Comment by muratg** [comment]
_From @ejsmith on February 25, 2016 3:59_

I don't think anything in the core interfaces needs to be changed for this, right? If so, this type of functionality really needs to be in another package. I am personally trying to get them to move all extension methods out to another package because the simpler we keep this abstractions package, the more chance it has of becoming the defacto standard for .NET logging and that would be a huge win.

**Comment by muratg** [comment]
_From @davidfowl on February 25, 2016 4:24_

This should be moved to either basic middleware or hosting

**Comment by muratg** [comment]
_From @rynowak on February 26, 2016 20:30_

> If so, this type of functionality really needs to be in another package. 

Yup. That's how we'd do it.

**Comment by muratg** [comment]
@Eilon anyone with some cycles to take this one?

**Comment by Eilon** [comment]
@javiercn

**Comment by muratg** [comment]
@rynowak Will this be in the default template?

**Comment by rynowak** [comment]
No, this isn't really a template sort of thing. It's just one opinionated way of how to do correlation across multiple servers/services.

**Comment by Eilon** [comment]
@rynowak we're trying to figure out if this is must-have for v1.

**Comment by rynowak** [comment]
I don't think so. This works 99% as well as an OOB or sample.

**Comment by cwe1ss** [comment]
I think it doesn't have to be in the framework but some kind of sample would be great. I'm pretty sure people will want to modify stuff like this anyway. E.g. we might want to add the originating machine name and so on.

**Comment by rajarameshvarma** [comment]
Is there any plan to implement this or any sample available?

**Comment by Tratcher** [comment]
@glennc

**Comment by glennc** [comment]
@rajarameshvarma We are starting some planning on flowing correlation Ids, it is being worked on in conjunction with some internal partner teams and isn't really ready to show anything yet. There is also a community member working on plugging into Zipkin (http://zipkin.io/) but I am not sure if it turned into anything yet.

Have you already tried something and are stuck or are you just looking for examples at the moment?

**Comment by kevin-work** [comment]
@rajarameshvarma I came across this [blog](https://mderriey.github.io/2016/11/18/correlation-id-with-asp-net-web-api/), which seems like what you are looking for?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Hosting/issues/939 for progress on this.
