### ISSUE TITLE
Response Compression not working correctly for React projects

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [aspnet/BasicMiddleware#324]
I follow the doc ( https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.1&tabs=aspnetcore2x#configuration ) and found that the compression only works when debugging. My ASP.NET core version is 2.1.0-preview2-final with create-react-app.

**Comment by Tratcher** [comment]
Insufficient detail. I suggest moving this to stackoverflow.com where they can help you formulate the right questions. See the asp.net-core tag https://stackoverflow.com/questions/tagged/asp.net-core.

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
