### ISSUE TITLE
Compression not working depeding on User-Agent

### ISSUE THREAD

**Issue by agustins** [aspnet/BasicMiddleware#334]
I have an Angular application using the new template from net core sdk 2.1.

With this configuration:

``` csharp
public void Configure(IApplicationBuilder app)
{
    app.UseResponseCompression();
    app.UseStaticFiles();
    app.UseSpaStaticFiles();
}

public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
    services.AddResponseCompression();

    // In production, the Angular files will be served from this directory
    services.AddSpaStaticFiles(configuration =>
    {
        configuration.RootPath = "angular/out";
    });
}
```
if the User-Agent header is present in the header, content is not compressed:

![wrong](https://user-images.githubusercontent.com/1606378/41241098-81708582-6d72-11e8-889f-119ccf5e8b1e.png)

Removing User-Agent header, response is compressed:

![ok](https://user-images.githubusercontent.com/1606378/41241099-819836cc-6d72-11e8-93ca-bf1d55f161b4.png)

**Comment by Tratcher** [comment]
User agent should not be a factor here. What happens if you don't use UseSpaStaticFiles?

**Comment by agustins** [comment]
Removing UseSpaStaticFiles the behaviour is the same

**Comment by muratg** [comment]
Closing this. @agustins please let us know if you have a network trace that you can share.
