### ISSUE TITLE
[Breaking Change] Add duplicate constructor for HSTS middleware

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BasicMiddleware#339]
See https://github.com/aspnet/BasicMiddleware/pull/338#issuecomment-397109240

Add a duplicate constructor. Make sure to place it second because DI has ordering issues.

**Comment by muratg** [comment]
@Tratcher it looks like https://github.com/aspnet/BasicMiddleware/pull/327 made the constructor change. Please do the needful. 

cc @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
Once you do this you'll need to remove the breakingchanges file we added in aspnet/BasicMiddleware#338.
