### ISSUE TITLE
Add HTTP compression middleware

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/BasicMiddleware#34]
Add middleware for doing HTTP response compression. Should support GZIP and Brotli. Would need to be configurable to allow control of:
- enabled compression algorithms (maybe support compression providers?)
- response content types to compress (should default to a known good list)
- buffering behavior

E.g.:

``` c#
public void Configure(IApplicationBuilder app)
{
    app.UseResponseCompression();
    app.UseStaticFiles();
    app.Run(async context =>
    {
        context.Response.ContentType = "text/plain";
        await context.Response.WriteAsync("Hello compressed!");
    });
}
```

**Comment by AlirezaP** [comment]
good idea.
in addition its not bad  for add some attribute like "https://github.com/AlirezaP/TagCompressor.Net" and "https://github.com/AlirezaP/TagCompressor.NetCore".

**Comment by AlirezaP** [comment]
@DamianEdwards what's your opinion about this?
[AP.AspNet.ResponseCompression](https://github.com/AlirezaP/AP.AspNet.ResponseCompression/tree/master)
it's a middleware for ResponseCompression but it's not for GZIP or Brotli.

**Comment by DamianEdwards** [comment]
You're talking about HTML minification there, rather than compression. It's also interesting but IMO is much better handled at compile time rather than run time. This issue is specifically about adding middleware to support [HTTP compression](https://en.wikipedia.org/wiki/HTTP_compression).

**Comment by AlirezaP** [comment]
i'm get it.
thank you.

**Comment by AlirezaP** [comment]
@DamianEdwards  
I have added gzip and it worked, but first request.
I mean in the first request, the response page is null (context.Response.Body) but when you refresh the page (just once) it works correctly after that.
[AP.AspNet.ResponseCompression ](https://github.com/AlirezaP/AP.AspNet.ResponseCompression/blob/master/src/AP.AspNet.ResponseCompression/ResponseGzipCompressMiddleware.cs)
this is in runtime, isn't it?
if yes, would you please tell me how I can handle it in compile time?

**Comment by Tratcher** [comment]
@AlirezaP Your Invoke method is still very broken which is why it doesn't work for the first request.  Let's discuss this in your repo instead.

**Comment by AlirezaP** [comment]
sure. thanks

**Comment by AndreiGorlov** [comment]
@AlirezaP 
> I have added gzip and it worked, but first request.
> I mean in the first request, the response page is null (context.Response.Body) but when you refresh the page (just once) it works correctly after that.(I don't know why but I have to solve it)

You need to update context.Response.Headers["Content-Length"] with actual compressed buffer length.

https://gist.github.com/AndreiGorlov/388745f59145209fa951

**Comment by h0useRus** [comment]
I made more close to RFC standard
` internal class ContentCompressionMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly ContentCompressionOptions _options;
        public ContentCompressionMiddleware(RequestDelegate next, IOptions<ContentCompressionOptions> options)
        {
            Ensure.Argument.NotNull(next, nameof(next));
            Ensure.Argument.NotNull(options, nameof(options));
            _next = next;
            _options = options.Value;
        }

        public async Task Invoke(HttpContext context)
        {
            var requestHeaders = new RequestHeaders(context.Request.Headers);
            // As per RFC2616.14.3:
            // Ignores encodings with quality == 0
            // If multiple content-codings are acceptable, then the acceptable content-coding with the highest non-zero qvalue is preferred.
            var encodingName =
                   (from encoding in requestHeaders.AcceptEncoding
                    let quality = encoding.Quality ?? 1.0
                    where quality > 0
                    orderby quality descending
                    select encoding.Value.ToLowerInvariant()).FirstOrDefault();
            encodingName = encodingName == "*" || encodingName == "compress" ? CompressionType.GZip.ToString() : encodingName;

            CompressionType compressionType;
            // no compression
            if (!Enum.TryParse(encodingName, true, out compressionType))
            {
                await _next.Invoke(context).ConfigureAwait(false);
                return;
            }

            using (var internalStream = new MemoryStream())
            {
                var bodyStream = context.Response.Body;
                context.Response.Body = internalStream;

                await _next.Invoke(context).ConfigureAwait(false);

                if (!context.Response.HasStarted && internalStream.Length >= _options.MinimumLength)
                {
                    context.Response.Headers.Append(HeaderNames.ContentEncoding, new[] { compressionType.ToString().ToLowerInvariant() });
                    await Compress.GetCompressor(compressionType).CompressAsync(internalStream, bodyStream).ConfigureAwait(false);
                    if (context.Response.Headers[HeaderNames.ContentLength].Count > 0)
                    {
                        context.Response.Headers[HeaderNames.ContentLength] = bodyStream.Length.ToString();
                    }
                    context.Features.Set(new CompressionFeature(compressionType));
                }
                else
                {
                    internalStream.Seek(0, SeekOrigin.Begin);
                    await internalStream.CopyToAsync(bodyStream).ConfigureAwait(false);
                }
            }
        }
    }`

**Comment by RehanSaeed** [comment]
@h0useRus There is already a PR being worked on [here](https://github.com/aspnet/BasicMiddleware/pull/52).

**Comment by Yves57** [comment]
@h0useRus Thank you for you idea! I will add your Quality idea in my PR.

**Comment by tkrotoff** [comment]
This can be closed, see:
- #52 has been merged
- This is included inside [ASP.NET Core 1.1](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/)
- Example: [Using Response Compression Middleware in ASP.NET Core](http://dotnetthoughts.net/using-response-compression-middleware-in-aspnet-core/)
