### ISSUE TITLE
HostFilteringMiddleware uses C# interopolated strings for tracing

### ISSUE THREAD

**Issue by daniel-white** [aspnet/BasicMiddleware#362]
`HostFilteringMiddleware` is using C# interopolated strings instead of passing the arguments off to the `ILogger`. I'm using Serilog which will cache the trace message, so if that changes, it will balloon. Plus, its causing more work for the middleware when the tracing is not turned up.

**Comment by Tratcher** [comment]
Agreed. Interested in sending a PR?

**Comment by Tratcher** [comment]
release/2.2
