### ISSUE TITLE
Direct middleware for http methods

### ISSUE THREAD

**Issue by neville-nazerane** [aspnet/BasicMiddleware#368]
It would be nice some extension functions for `IApplicationBuilder` like `UseGet()` or `UseHttpGet()` that could add a middleware that directly matches to HTTP GET and to the specified path (similarly for POST, PUT and DELETE). It could be helpful in small web apps for adding some simple middlewares quick and with a high performance. I was planning to make a PR for the same with unit tests and I had to check if this makes sense. I had planned something similar to the following overloads for `UseGet()`, `UsePost()`, `UsePut()` and `UseDelete()`:

1. _`UseGet(PathString path, string responseText)`_: On matching the path and method, prints `responseText` with HTTP OK

2. _`UseGet(PathString path, Action<HttpContext> middleware)`_: On matching the path and method, passes the context to `middleware`.

3. _`UseGet(PathString path, Func<HttpContext, Task> middleware)`_: Async variant of the above. 

4. _`UseGet(PathString path, Func<HttpContext, Func<Task>, Task> middleware)`_:  On matching the path and method, passes the context and next delegate to `middleware`.

**Comment by Tratcher** [comment]
@JamesNK This looks like Endpoints. Want to show them your progress?

**Comment by JamesNK** [comment]
That's exactly what we are working on for 3.0.

https://github.com/aspnet/Routing/blob/ede9ff8e50a37053a25076eb767ee7ea46a0f0ea/samples/RoutingSample.Web/UseEndpointRoutingStartup.cs

**Comment by muratg** [comment]
Tracked elsewhere. Closing this one.
