### ISSUE TITLE
Enable response compression support for WebAssembly by default

### ISSUE THREAD

**Issue by danroth27** [aspnet/BasicMiddleware#376]
Currently for Blazor we explicitly enable response compression support for WebAssembly (`application/wasm`). Given that WebAssembly is picking up, it makes sense to enable response compression for WebAssembly by default.

**Comment by Tratcher** [comment]
@muratg @shirhatti this is a XS ask for 2.2.

**Comment by muratg** [comment]
@Tratcher what's the PR looking like? Single line addition to https://github.com/aspnet/BasicMiddleware/blob/release/2.2/src/Microsoft.AspNetCore.ResponseCompression/ResponseCompressionDefaults.cs? 

I think it's fine, but I'll let @shirhatti make a decision.

**Comment by Tratcher** [comment]
Right. I'll send it.
