### ISSUE TITLE
Url Rewrite custom response

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#56]
Currently not supporting custom responses for Url Rewrite Rules (part of the match). This feature seemed rarely used, but should be considered in the final implementation.
Ex:

```
<action type="CustomResponse" statusCode="503"  
subStatusCode="0"  
statusReason="Site is unavailable"  
statusDescription="Site is down for maintenance" />  
```

**Comment by mikaelm12** [comment]
Resolved in https://github.com/aspnet/BasicMiddleware/pull/200
