### ISSUE TITLE
Add more comprehensive code rules

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#57]
In the initial sample/ review of the rewrite module, the standard builder model was used to add rules. There are a few simple examples that exist, but these should be verified for operation and more code rules should be added.
Right now we have rules like `RedirectRule` or `RedirectScheme`, but a review of these should be done as well as more rules added (check if file exists, rewriting query, etc).

**Comment by natemcmaster** [comment]
@muratg this seems like an ambitious goal that probably won't fit in 1.1. Can we bump this to post- 1.1?

**Comment by muratg** [comment]
@natemcmaster sounds good. Putting in backlog for now, and we'll reconsider after 1.1.

**Comment by jkotalik** [comment]
Closing as this isn't ask.
