### ISSUE TITLE
Url Rewrite Checklist

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#67]
**Features implemented in Url Rewrite:**

Elements/Attributes in rules:
- [x] Rules
- [x] Name
- [x] Enabled
- [x] PatternSyntax ECMAScript
- [x] ExactMatch
- [x] StopProcessing
- [x] Matches
- [x] Conditions: MatchAll
- [x] Conditions: MatchAny
- [x] TrackAllCaptures
- [x] IsFile
- [x] IsDirectory
- [x] IgnoreCase
- [x] Negate
- [x] Action:Rewrite
- [x] Action:Redirect
- [x] AppendQueryString
- [x] RedirectType
- [x] Action:AbortRequest

Server Variables (common ones supported for now, TODO on complete list)

**Features that are not implemented in UrlRewrite:**
- [x] Global Rules
- [ ] Outbound Rules
- [x] RewriteMaps
- [x] Custom Server Variables

Elements/Attributes in rules:
- [ ] WildCard
- [ ] ServerVariables 
- [ ] Action:CustomResponse
- [ ] LogRewrittenUrl

**Comment by davidpeden3** [comment]
added:
- global rules support: https://github.com/aspnet/BasicMiddleware/pull/169
- rewrite map support: https://github.com/aspnet/BasicMiddleware/pull/168
- custom request/response headers via server variables: https://github.com/aspnet/BasicMiddleware/pull/184

**Comment by jkotalik** [comment]
Closing due to supporting everything we need and we are not doing outbound rules.
