### ISSUE TITLE
Refactor ModRewriteRedirect/Rewrite Action and Redirect/Rewrite Action together.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#76]
Actions occur once the rule has passed. These can be consolidated into one class. Thought they needed to be distinct because of mod_rewrite allowing for more options, but we can probably construct UrlRewrite rules with defaults in mod_rewrite.
See: 
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/ModRewrite/ModRewriteRedirectAction.cs
Versus
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/UrlActions/RedirectAction.cs

**Comment by ZestyBread** [comment]
See #79

**Comment by natemcmaster** [comment]
Resolved by https://github.com/aspnet/BasicMiddleware/pull/77
