### ISSUE TITLE
Leading slash throws off rewrite pattern match

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BasicMiddleware#78]
**Repro**
```c#
var options = new RewriteOptions();
options.Rewrite("/app/(.+)", "/app?q={R:1}"); // "/app?q=$1" after #77
app.UseRewriter(options);
```
Request to localhost:5000/app/abcd
**Expected**
Rewrites to  localhost:5000/app?q=abcd

**Actual**
No rewrite. The match condition is not met because the `UrlRewriteRule` strips the leading slash

https://github.com/aspnet/BasicMiddleware/blob/28133b6808224a55348dc7054f24ce455c0937d7/src/Microsoft.AspNetCore.Rewrite/Internal/UrlRewriteRule.cs#L40

cc @ZestyBread

**Comment by ZestyBread** [comment]
The standard in mod_rewrite and UrlRewrite is to match on no leading slash.
Search for leading slash in:
https://www.sitepoint.com/apache-mod_rewrite-examples/

Also I didn't find any docs on IIS, but this is the PM's set of rewrite rules which all exclude the leading slash.
http://ruslany.net/2009/04/10-url-rewriting-tips-and-tricks/

**Comment by muratg** [comment]
By design per @jkotalik's comment.
