### ISSUE TITLE
Redirects need to add the path base to the path when setting location header.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#85]
As title says. 
See:
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/UrlActions/RedirectAction.cs
and 
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/CodeRules/RedirectRule.cs

**Comment by muratg** [comment]
@mikaelm12 -- we think this may have been fixed already, so assigning to you for verification.

**Comment by mikaelm12** [comment]
Looks good to me
