### ISSUE TITLE
Add cookie and environment variable actions

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BasicMiddleware#94]
mod_rewrite specific thing. These flags modify the cookie and environment variable respectively.
See:
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Rewrite/Internal/UrlActions/ChangeCookieAction.cs

**Comment by muratg** [comment]
Environment variable actions is not possible with our current implementation -- they're set per process.

Cookie ones could be done.

**Comment by muratg** [comment]
Assigning to @natemcmaster to remove the Environment one. We'll either implement or remove Cookie one before 1.1.
