### ISSUE TITLE
Using Rewrite to Redirect to Canonical URL's for Better SEO

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/BasicMiddleware#95]
To improve Search Engine Optimization SEO, there should only be a single URL for each resource. Case differences and/or URL's with/without trailing slashes are treated as different URL's by search engines (See [Google](http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html)'s comments and [Bing](http://blogs.bing.com/webmaster/2012/01/26/moving-content-think-301-not-relcanonical)'s).

It would be greate to write an extension method for `IApplicationBuilder` called `UseRedirectToCanonicalUrl` that does this. Here are the special considerations:
1. The host name is treated differently by search engines. All of the following are equivelant:
   - http://example.com
   - http://example.com/
   - http://EXAMPLE.com
2. `IOptions<RouteOptions>` can be used to determine the `AppendTrailingSlash` and `LowercaseUrls` settings. These can be used to work out whether to add or remove a trailing slash and also whether we should be lower-casing URL's.
3. You need to deal with exceptions to the rule. For example, if you have routes to dynamically generate robots.txt, sitemap.xml etc. you don't want to redirect these to add trailing slashes, nor do you care about case differences as these routes are effectively being treated as if they were static files.
4. Sometimes you want to have case-sensitive query strings. ASP.NET Identity for example requires them. This is another exception to the rule that needs to be handled. Perhaps a `LowercaseQueryStrings` property could be added to `IOptions<RouteOptions>`.

I have already written a [RedirectToCanonicalUrlAttribute MVC Core filter](https://github.com/ASP-NET-MVC-Boilerplate/Framework/blob/master/Source/MVC6/Boilerplate.AspNetCore/Filters/RedirectToCanonicalUrlAttribute.cs) to do the above and I've been thinking about converting it to middleware, then I saw this project and now think it can be used for this purpose. I provide two ways of providing exceptions to the rule:
- [NoTrailingSlashAttribute](https://github.com/ASP-NET-MVC-Boilerplate/Framework/blob/master/Source/MVC6/Boilerplate.AspNetCore/Filters/NoTrailingSlashAttribute.cs) - Don't redirect to add a trailing slash. Useful in the above robots.txt example.

```
[NoTrailingSlash]
[Route("robots.txt", Name = "GetRobotsText")]
public IActionResult RobotsText() {}
```
- [NoLowercaseQueryStringAttribute](https://github.com/ASP-NET-MVC-Boilerplate/Framework/blob/master/Source/MVC6/Boilerplate.AspNetCore/Filters/NoLowercaseQueryStringAttribute.cs) - Do not lower-case the query string using a redirect. Allows the use of case-sensitive query strings.

```
[NoLowercaseQueryString]
[Route("foo", Name = "GetFoo")]
public IActionResult Foo(string caseSensitiveQueryParameter) {}
```

@ZestyBread I watched the community standup this morning, are you still working at Microsoft? Would you be interested in a PR?

**Comment by muratg** [comment]
It's @ZestyBread's last day of internship today. 

@DamianEdwards Would we be interested in something like this?

**Comment by ZestyBread** [comment]
I like both of these ideas for sure! I wouldn't be the one managing the PR anymore, but someone in the ASP.NET team would be instead. 

I think the trailing slash can be handled with standard redirects for now, for example
.Redirect("(.*)/", "$1") will check for a trailing slash and redirect without the trailing slash. 
You can easily invert this if you want a trailing slash.
For the To Lowercase on the Path, I think it would be more difficult, but it wouldn't be difficult for us to handle, along with the query string. You can also create your own rule which checks the http's context path and query and use string functions instead (there is an overload that takes in an Action<RewriteContext>).

Design wise, I'm not sure if having it as an attribute or an extension is better. 

Feel free to make a PR also man and @ me on it, I'll review appropriately.

**Comment by RehanSaeed** [comment]
@ZestyBread 

Using Regex for the trailing slash redirect would work but it does not need to happen on the home page of a site as a URL's with or without a trailing slash are equivalent for the home page which is a special case. Secondly, I'm not sure performance would be that great with Regex.

The overload that takes the Action is exactly the one I'm interested in. I'm thinking I could copy and paste the code from my filter in there and it would work.

As you say, I'm also not sure if a filter or middleware would be best in this situation.

@muratg @DamianEdwards Would you be interested in a PR?

**Comment by natemcmaster** [comment]
My initial reaction to this is that the feature is beyond the scope of the rewrite middleware. Although it may share some capabilities with the rewrite middleware, it seems more appropriate to have a dedicated SEO middleware for these features. A separate middleware is more likely to be a cleaner, faster implementation.

**Comment by mikaelm12** [comment]
I'm not sure that this is something that we'd add to this project but I do like the idea and it's a simple enough middleware. I hacked together a sample version of a canonical url middleware [here](https://github.com/mikaelm12/Canonical-Url-Middleware/tree/master/Middleware)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
